extends SceneTree

var failures := 0
var assertions := 0

func _initialize() -> void:
	if "--self-test-failure" in OS.get_cmdline_user_args():
		_expect(false, "intentional harness failure")
	else:
		_run_tests()
	if failures:
		printerr("FAILED: %d of %d assertions" % [failures, assertions])
		quit(1)
	else:
		print("PASS: %d assertions" % assertions)
		quit(0)

func _run_tests() -> void:
	var planar := _fixture("res://fixtures/planar-v1.json")
	var multi := _fixture("res://fixtures/multi-curve-v1.json")
	var braid := _fixture("res://fixtures/braid-v1.json")
	if planar == null or multi == null or braid == null: return
	_expect(planar.data.kind == "planar", "planar kind")
	_expect(planar.data.surface.objects.size() == 4, "four planar objects")
	_expect(planar.data.surface.objects[0].id == "p1", "stable object ID")
	_expect(planar.data.curves[0].cuts == [], "exact empty itinerary")
	var canonical_planar := planar.to_json()
	_expect(canonical_planar == JSON.stringify(planar.to_dict(), "\t", false, true) + "\n", "cached canonical JSON exactly matches normalized serialization")
	var leaked := planar.data; leaked.title = "Mutated copy"
	_expect(planar.data.title == "Generic planar import fixture" and planar.to_json() == canonical_planar, "external dictionary mutation cannot change record or cached canonical JSON")
	_expect(planar.data.style.marked_point_color == "#006fff", "blue marks")
	_expect(planar.data.style.boundary_color == "#8b8b8b", "gray boundaries")
	_expect(planar.data.curves[0].color == "#ff00d4", "magenta curve default")
	_expect(not planar.data.allow_intersections, "intersections remain explicit")
	_expect(multi.data.surface.objects.size() == 6 and multi.data.curves.size() == 3, "multi-curve fixture has six stable points and three curves")
	_expect(multi.data.curves[1].id == "editable" and multi.data.curves[1].cuts == [0], "multi-curve fixture keeps initial exact itinerary")
	_expect(braid.data.braid.word == [1, -2, 3, -4, 5], "braid word order and signs preserved")
	_expect(braid.data.braid.direction == "bottom-to-top", "braid direction preserved")
	var braid_states := BraidTimeline.orders(braid)
	_expect(braid_states == [[1, 2, 3, 4, 5, 6], [2, 1, 3, 4, 5, 6], [2, 3, 1, 4, 5, 6], [2, 3, 4, 1, 5, 6], [2, 3, 4, 5, 1, 6], [2, 3, 4, 5, 6, 1]], "independent six-strand transported identities at every literal prefix")
	var positive_up := BraidTimeline.crossing(braid, 0, "bottom-to-top")
	var positive_down := BraidTimeline.crossing(braid, 0, "top-to-bottom")
	_expect(positive_up.ok and positive_down.ok and positive_up.upper_left_over_upper_right and positive_down.upper_left_over_upper_right and positive_up.over_id == 2 and positive_down.over_id == 1, "positive upper-left-over-upper-right crossing is fixed in both physical presentations")
	var negative_up := BraidTimeline.crossing(braid, 1, "bottom-to-top")
	var negative_down := BraidTimeline.crossing(braid, 1, "top-to-bottom")
	_expect(negative_up.ok and negative_down.ok and not negative_up.upper_left_over_upper_right and not negative_down.upper_left_over_upper_right and negative_up.over_id == 1 and negative_down.over_id == 3, "negative crossing retains complementary over strand in either presentation")
	_expect(not BraidTimeline.crossing(braid, 5).ok and not BraidTimeline.crossing(braid, 0, "sideways").ok, "crossing inspector rejects missing index and unsupported presentation")
	var braid_original := braid.to_json()
	var insert_braid := braid.with_braid_word_edit("insert", 2, -2)
	_expect(insert_braid.ok and insert_braid.document.data.braid.word == [1, -2, -2, 3, -4, 5] and braid.to_json() == braid_original, "insertion retains literal adjacent inverse/same terms without reduction and does not mutate source")
	var replace_braid := braid.with_braid_word_edit("replace", 1, 2)
	_expect(replace_braid.ok and replace_braid.document.data.braid.word == [1, 2, 3, -4, 5], "replacement preserves exact positions and signs of sibling generators")
	var delete_braid := braid.with_braid_word_edit("delete", 1)
	_expect(delete_braid.ok and delete_braid.document.data.braid.word == [1, 3, -4, 5], "deletion removes only the selected crossing")
	_expect(not braid.with_braid_word_edit("insert", 6, 1).ok and not braid.with_braid_word_edit("replace", 5, 1).ok and not braid.with_braid_word_edit("delete", -1).ok, "invalid edit positions are rejected")
	_expect(not braid.with_braid_word_edit("insert", 1, 0).ok and not braid.with_braid_word_edit("replace", 1, 6).ok and not braid.with_braid_word_edit("reduce", 1, 1).ok, "zero, out-of-range, and unsupported braid edits are rejected")
	var braid_history := DiagramEditHistory.new()
	braid_history.set_document(braid)
	var rejected_braid := braid_history.edit_braid_word("insert", 0, 0, PythonGeometryBridge.render)
	_expect(not rejected_braid.ok and braid_history.current.to_json() == braid_original and not braid_history.can_undo(), "rejected braid command leaves source and history exact")
	var braid_committed := braid_history.edit_braid_word("insert", 2, -2, PythonGeometryBridge.render)
	_expect(braid_committed.ok and braid_history.undo_stack.size() == 1 and braid_committed.selection.index == 2, "Python-validated braid insertion is one indexed command")
	var braid_changed := braid_history.current.to_json()
	var braid_render := PythonGeometryBridge.render(braid_history.current)
	_expect(braid_render.ok and braid_render.manifest.kind == "braid", "edited braid is accepted by fixed Python publication bridge")
	_expect(braid_history.undo().document.to_json() == braid_original and braid_history.redo().document.to_json() == braid_changed, "braid undo and redo reproduce signed word exactly")
	var braid_rows := braid.summary_rows()
	_expect("entry [1, 2, 3, 4, 5, 6]  exit [2, 1, 3, 4, 5, 6]" in braid_rows[1], "first strand transport")
	var planar_records := planar.inspector_records()
	_expect(planar_records[0].kind == "object" and planar_records[0].id == "p1", "inspector maps row to stable object ID")
	_expect(planar_records[4].kind == "curve" and planar_records[4].id == "arc1", "inspector maps row to stable curve ID")
	var braid_records := braid.inspector_records()
	_expect(braid_records[1].kind == "crossing" and braid_records[1].index == 0, "inspector maps row to exact crossing index")
	var round_trip := DiagramDocument.parse(planar.to_json())
	_expect(round_trip.ok, "normalized JSON reopens")
	if round_trip.ok:
		_expect(round_trip.document.data == planar.data, "round trip is lossless")
		var camera_state := {"zoom": 2.0, "pan": Vector2(30, -10)}
		_expect(round_trip.document.data == planar.data and camera_state.zoom == 2.0, "camera state is separate")
	var edit_candidates: Array[Dictionary] = []
	var label_candidate := planar.to_dict()
	label_candidate.labels[0].x = -111.25
	edit_candidates.append(label_candidate)
	var object_candidate := planar.to_dict()
	object_candidate.surface.objects[1].x = -25.5
	edit_candidates.append(object_candidate)
	var curve_candidate := multi.to_dict()
	curve_candidate.curves[1].cuts = [0, 6]
	edit_candidates.append(curve_candidate)
	var braid_candidate := braid.to_dict()
	braid_candidate.braid.word.insert(2, -2)
	edit_candidates.append(braid_candidate)
	for candidate in edit_candidates:
		var internal_candidate := DiagramDocument._from_edit_candidate(candidate)
		var text_candidate := DiagramDocument.parse(JSON.stringify(candidate))
		_expect(internal_candidate.ok and text_candidate.ok and internal_candidate.document.to_json() == text_candidate.document.to_json(), "bounded edit candidate normalizes identically to the full text parser")
	var rejected_candidates: Array[Dictionary] = []
	var candidate_unknown := planar.to_dict(); candidate_unknown.future_field = true
	rejected_candidates.append(candidate_unknown)
	var candidate_duplicate := planar.to_dict(); candidate_duplicate.surface.objects[1].id = "p1"
	rejected_candidates.append(candidate_duplicate)
	var candidate_cuts := multi.to_dict(); candidate_cuts.curves[1].cuts = [0, 0]
	rejected_candidates.append(candidate_cuts)
	var candidate_generator := braid.to_dict(); candidate_generator.braid.word = [6]
	rejected_candidates.append(candidate_generator)
	var candidate_style := planar.to_dict(); candidate_style.style.curve_color = "magenta"
	rejected_candidates.append(candidate_style)
	for candidate in rejected_candidates:
		var internal_rejection := DiagramDocument._from_edit_candidate(candidate)
		var text_rejection := DiagramDocument.parse(JSON.stringify(candidate))
		_expect(not internal_rejection.ok and not text_rejection.ok and internal_rejection.error == text_rejection.error, "bounded edit candidate rejects with the same schema error as the full text parser")
	var save_path := "user://round-trip.json"
	_expect(planar.save_path(save_path).is_empty(), "save succeeds")
	_expect(FileAccess.get_file_as_string(save_path) == canonical_planar, "save writes the exact cached canonical bytes")
	var reopened := DiagramDocument.load_path(save_path)
	_expect(reopened.ok and reopened.document.data == planar.data, "saved recipe reopens exactly")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(save_path))
	_reject("{", "malformed JSON")
	_reject("[]", "non-object document")
	_reject('{"format":"surface-diagrams","version":1,"version":1,"kind":"planar","surface":{"width":20,"height":20,"objects":[]}}', "duplicate JSON field")
	_reject('{"format":"surface-diagrams","version":1,"\\u0076ersion":1,"kind":"planar","surface":{"width":20,"height":20,"objects":[]}}', "escaped duplicate JSON field")
	var future := planar.to_dict(); future.version = 2
	_reject(JSON.stringify(future), "future version")
	var unknown := planar.to_dict(); unknown.future_field = 3
	_reject(JSON.stringify(unknown), "unknown field")
	var duplicate_id := planar.to_dict(); duplicate_id.surface.objects[1].id = "p1"
	_reject(JSON.stringify(duplicate_id), "duplicate object ID")
	var reordered := planar.to_dict(); reordered.surface.objects[1].x = -130
	_reject(JSON.stringify(reordered), "object reordering")
	var outside := planar.to_dict(); outside.surface.objects[0].x = -200
	_reject(JSON.stringify(outside), "object on outer ellipse")
	var nonminimal := planar.to_dict(); nonminimal.curves[0].cuts = [2, 2]
	_reject(JSON.stringify(nonminimal), "nonminimal itinerary")
	var same_endpoint := planar.to_dict(); same_endpoint.curves[0].end = same_endpoint.curves[0].start
	_reject(JSON.stringify(same_endpoint), "arc with equal endpoints")
	var adjacent_cut := planar.to_dict(); adjacent_cut.curves[0].cuts = [0]
	_reject(JSON.stringify(adjacent_cut), "terminal cut adjacent to endpoint")
	var bad_loop := planar.to_dict(); bad_loop.curves = [{"id": "loop1", "kind": "loop", "cuts": [0]}]
	_reject(JSON.stringify(bad_loop), "odd loop itinerary")
	var bad_generator := braid.to_dict(); bad_generator.braid.word = [6]
	_reject(JSON.stringify(bad_generator), "out-of-range braid generator")
	var identity_braid := braid.to_dict(); identity_braid.braid.word = []
	var identity_result := DiagramDocument.parse(JSON.stringify(identity_braid))
	_expect(identity_result.ok and identity_result.document.data.braid.word.is_empty(), "empty braid word is retained")
	var empty_history := DiagramEditHistory.new()
	empty_history.set_document(identity_result.document)
	_expect(not empty_history.edit_braid_word("delete", 0).ok, "empty braid cannot delete a nonexistent crossing")
	var only_crossing := empty_history.edit_braid_word("insert", 0, -1, PythonGeometryBridge.render)
	_expect(only_crossing.ok and only_crossing.document.data.braid.word == [-1] and BraidTimeline.orders(only_crossing.document)[1] == [2, 1, 3, 4, 5, 6], "empty braid accepts one signed generator with computed identities")
	var editor := BraidEditor.new()
	editor.configure(braid, braid.inspector_records()[1], true)
	_expect(editor.step == 5 and editor.direction == "bottom-to-top" and editor.visible, "braid editor defaults to complete imported view")
	editor.set_step(0)
	_expect(editor.step == 0 and "[1, 2, 3, 4, 5, 6]" in editor.detail.text, "step zero exposes exact identity configuration")
	editor.set_step(3)
	_expect(editor.step == 3 and "[2, 3, 4, 1, 5, 6]" in editor.detail.text and braid.to_json() == braid_original, "scrub derives exact third prefix without mutating imported recipe")
	editor.set_direction("top-to-bottom")
	_expect(editor.direction == "top-to-bottom" and braid.to_json() == braid_original and editor.step == 3, "presentation toggle leaves word, sign, and timeline position unchanged")
	editor.set_step(5)
	editor.toggle_play()
	_expect(editor.playing and editor.step == 0 and braid.to_json() == braid_original, "play at endpoint restarts from initial configuration without changing source")
	editor.advance(1.2)
	_expect(editor.step == 2 and editor.playing and "[2, 3, 1, 4, 5, 6]" in editor.detail.text, "timed playback lands on exact independent second prefix")
	editor.advance(2.0)
	_expect(editor.step == 5 and not editor.playing and editor.play_button.text == "Play", "playback stops at final supplied configuration")
	editor.configure(braid, braid.inspector_records()[2], false)
	_expect(editor.step == 5 and editor.direction == "top-to-bottom" and editor.index_spin.value == 1, "reconfigure retains separate view state and follows crossing index")
	editor.free()
	var executable := planar.to_dict(); executable.script = "res://evil.gd"
	_reject(JSON.stringify(executable), "imported script field")
	var huge := " ".repeat(DiagramDocument.MAX_BYTES) + "{}"
	var huge_result := DiagramDocument.parse(huge)
	_expect(not huge_result.ok, "oversized document")
	var canvas := DiagramCanvas.new()
	canvas.document = planar
	var before := planar.to_json()
	canvas.zoom_at(Vector2(100, 100), 1.5)
	canvas.pan = Vector2(20, 30)
	_expect(planar.to_json() == before, "canvas navigation does not mutate records")
	canvas.select_record(planar_records[4])
	_expect(canvas.selected_record.id == "arc1" and planar.to_json() == before, "selection is separate from records")
	canvas.free()
	var planar_geometry := PythonGeometryBridge.render(planar)
	_expect(planar_geometry.ok and planar_geometry.svg.begins_with("<svg"), "Python bridge renders planar SVG")
	_expect(planar_geometry.ok and "tikzpicture" in planar_geometry.tikz, "Python bridge renders planar TikZ")
	var planar_image := Image.new()
	var planar_svg_error := planar_image.load_svg_from_buffer(planar_geometry.svg.to_utf8_buffer()) if planar_geometry.ok else FAILED
	_expect(planar_svg_error == OK and planar_image.get_width() > 0 and planar_image.get_height() > 0, "Godot decodes exact planar SVG")
	var braid_geometry := PythonGeometryBridge.render(braid)
	_expect(braid_geometry.ok and braid_geometry.manifest.kind == "braid", "Python bridge renders braid through fixed adapter")
	var braid_image := Image.new()
	var braid_svg_error := braid_image.load_svg_from_buffer(braid_geometry.svg.to_utf8_buffer()) if braid_geometry.ok else FAILED
	_expect(braid_svg_error == OK and braid_image.get_width() > 0 and braid_image.get_height() > 0, "Godot decodes exact braid SVG")
	_expect(planar.to_json() == before, "geometry bridge does not mutate records")
	var multi_geometry := PythonGeometryBridge.render(multi)
	_expect(multi_geometry.ok and multi_geometry.svg.begins_with("<svg"), "Python bridge accepts multi-curve fixture")
	var original_python := OS.get_environment("SURFACE_DIAGRAMS_PYTHON")
	OS.set_environment("SURFACE_DIAGRAMS_PYTHON", "/definitely-missing-surface-diagrams-python")
	var unavailable_geometry := PythonGeometryBridge.render(planar)
	OS.set_environment("SURFACE_DIAGRAMS_PYTHON", original_python)
	_expect(not unavailable_geometry.ok and unavailable_geometry.svg.is_empty(), "missing Python stays an explicit unavailable state")
	var history := DiagramEditHistory.new()
	history.set_document(planar)
	var original_source := planar.to_json()
	var moved := history.move_object("p2", -20.0)
	_expect(moved.ok and moved.document.data.surface.objects[1].x == -20.0, "history accepts a point move between neighbors")
	_expect(moved.document.data.surface.objects[1].id == "p2" and moved.document.data.curves[0].cuts == planar.data.curves[0].cuts, "point move preserves IDs and exact cut itinerary")
	var moved_source: String = history.current.to_json()
	var rejected_move := history.move_object("p2", 50.0)
	_expect(not rejected_move.ok and history.current.to_json() == moved_source, "point cannot pass its right neighbor")
	var rejected_geometry := history.move_object("p2", -25.0, func(_candidate): return {"ok": false, "error": "test geometry rejection"})
	_expect(not rejected_geometry.ok and history.current.to_json() == moved_source and history.undo_stack.size() == 1, "geometry rejection preserves accepted document and history")
	var undone := history.undo()
	_expect(undone.ok and undone.document.to_json() == original_source and history.can_redo(), "undo restores exact prior recipe")
	var redone := history.redo()
	_expect(redone.ok and redone.document.to_json() == moved_source and history.can_undo(), "redo restores exact accepted recipe")
	var serialized_history := history.to_state()
	_expect(serialized_history.keys() == ["current", "undo", "redo"] and serialized_history.undo[0].keys() == ["label", "selection", "before", "after"], "parsed history snapshots never enter serialized recovery data")
	var accepted_before_tamper := history.current.to_json()
	var cached_before: String = history.undo_stack[-1].before
	history.undo_stack[-1].before = "{invalid cached command"
	var tampered_audit := history.retention_audit()
	_expect(not tampered_audit.cache_aligned and tampered_audit.totals.stale_snapshot_count == 1, "retention audit exposes a serialized-command/cache mismatch without trusting either copy")
	var tampered_undo := history.undo()
	_expect(not tampered_undo.ok and "Stored undo record is invalid" in tampered_undo.error and history.current.to_json() == accepted_before_tamper and history.undo_stack.size() == 1 and not history.can_redo(), "undo cache cannot bypass a mutated serialized command")
	history.undo_stack[-1].before = cached_before
	_expect(history.retention_audit().cache_aligned, "retention audit returns to aligned after exact serialized command restoration")
	_expect(history.undo().ok and history.current.to_json() == original_source, "valid serialized undo still uses the exact accepted target after rejection")
	var cached_after: String = history.redo_stack[-1].after
	history.redo_stack[-1].after = "{invalid cached command"
	var tampered_redo := history.redo()
	_expect(not tampered_redo.ok and "Stored redo record is invalid" in tampered_redo.error and history.current.to_json() == original_source and history.redo_stack.size() == 1 and not history.can_undo(), "redo cache cannot bypass a mutated serialized command")
	history.redo_stack[-1].after = cached_after
	_expect(history.redo().ok and history.current.to_json() == moved_source, "valid serialized redo still uses the exact accepted target after rejection")
	var bounded_history := DiagramEditHistory.new()
	bounded_history.set_document(planar)
	var oldest_retained_target := ""
	for index in 101:
		var bounded_move := bounded_history.move_label("label1", Vector2(100.0 + index, -60.0))
		if index == 0: oldest_retained_target = bounded_move.document.to_json()
	var bounded_final := bounded_history.current.to_json()
	var bounded_audit := bounded_history.retention_audit()
	_expect(bounded_audit.format == DiagramEditHistory.RETENTION_AUDIT_FORMAT and bounded_audit.version == 1 and bounded_audit.history_limit == 100, "history retention audit is explicitly versioned")
	_expect(bounded_audit.totals.command_count == 100 and bounded_audit.totals.snapshot_count == 100 and bounded_audit.undo.command_count == 100 and bounded_audit.redo.command_count == 0, "history retention audit reports the exact 100-command runtime shape")
	_expect(bounded_audit.cache_aligned and bounded_audit.totals.stale_snapshot_count == 0 and bounded_audit.totals.missing_snapshot_count == 0 and bounded_audit.totals.orphan_snapshot_count == 0, "oldest-command eviction leaves no stale, missing, or orphaned runtime snapshot")
	_expect(bounded_audit.undo.first_snapshot_sha256 == DiagramEditHistory._sha256_text(oldest_retained_target), "oldest cached snapshot advances with the evicted command")
	_expect(bounded_audit.totals.serialized_command_bytes > bounded_audit.totals.command_source_bytes and bounded_audit.totals.logical_source_bytes > bounded_audit.totals.command_source_bytes, "history retention audit reports command serialization and logical source slots separately")
	_expect(bounded_audit.totals.snapshot_source_bytes == 0 and bounded_audit.undo.snapshot_source_bytes == 0 and bounded_audit.bounds.maximum_snapshot_source_bytes == 0, "runtime snapshots derive source from immutable documents instead of retaining duplicate strings")
	_expect(bounded_audit.within_source_bounds and bounded_audit.bounds.maximum_logical_source_bytes == 78905344, "history retention audit enforces the reduced conservative 100-command logical source envelope")
	for index in 100: bounded_history.undo()
	_expect(bounded_history.undo_stack.is_empty() and bounded_history.current.to_json() == oldest_retained_target, "100-command eviction keeps the parsed undo targets aligned")
	var undone_audit := bounded_history.retention_audit()
	_expect(undone_audit.cache_aligned and undone_audit.undo.snapshot_count == 0 and undone_audit.redo.snapshot_count == 100 and undone_audit.totals.command_count == 100, "complete undo transfers every retained snapshot without duplication")
	for index in 100: bounded_history.redo()
	_expect(bounded_history.redo_stack.is_empty() and bounded_history.current.to_json() == bounded_final, "100-command redo retains exact targets after oldest-command eviction")
	var redone_audit := bounded_history.retention_audit()
	_expect(redone_audit.cache_aligned and redone_audit.undo.snapshot_count == 100 and redone_audit.redo.snapshot_count == 0 and redone_audit == bounded_audit, "complete redo reproduces the byte-identical retention audit")
	var compact_bounded := bounded_history.to_compact_state()
	var legacy_bounded_bytes := JSON.stringify(bounded_history.to_state(), "", false, true).to_utf8_buffer().size()
	var compact_bounded_bytes := JSON.stringify(compact_bounded, "", false, true).to_utf8_buffer().size()
	_expect(compact_bounded.format == DiagramEditHistory.COMPACT_STATE_FORMAT and compact_bounded.version == 1 and compact_bounded.documents.size() == 101, "compact history is versioned and stores each endpoint document once")
	_expect(compact_bounded_bytes < legacy_bounded_bytes and compact_bounded.undo[0].before is int and compact_bounded.undo[0].after is int, "compact history replaces adjacent endpoint copies with bounded integer references")
	var compact_bounded_restore := DiagramEditHistory.new()
	var compact_bounded_result := compact_bounded_restore.restore_compact_state(compact_bounded)
	_expect(compact_bounded_result.ok and compact_bounded_restore.current.to_json() == bounded_final and compact_bounded_restore.undo_stack == bounded_history.undo_stack, "compact 100-command history restores the exact public command state")
	for index in 100: compact_bounded_restore.undo()
	_expect(compact_bounded_restore.current.to_json() == oldest_retained_target and compact_bounded_restore.redo_stack.size() == 100, "compact history reproduces all 100 exact undo endpoints")
	for index in 100: compact_bounded_restore.redo()
	_expect(compact_bounded_restore.current.to_json() == bounded_final and compact_bounded_restore.retention_audit() == bounded_audit, "compact history reproduces all 100 exact redo endpoints and runtime snapshots")
	var duplicate_compact: Dictionary = compact_bounded.duplicate(true)
	duplicate_compact.documents[1] = duplicate_compact.documents[0]
	_expect(not DiagramEditHistory.new().restore_compact_state(duplicate_compact).ok, "compact history rejects duplicate document slots")
	var bad_compact_reference: Dictionary = compact_bounded.duplicate(true)
	bad_compact_reference.undo[0].before = 999
	_expect(not DiagramEditHistory.new().restore_compact_state(bad_compact_reference).ok, "compact history rejects out-of-range document references")
	var label_move := history.move_label("label1", Vector2(15, -55))
	_expect(label_move.ok and label_move.document.data.labels[0].x == 15.0 and label_move.document.data.labels[0].y == -55.0, "label move is command based")
	var label_source: String = history.current.to_json()
	history.undo()
	var replacement_move := history.move_object("p2", -30.0)
	_expect(replacement_move.ok and not history.can_redo(), "a new edit clears redo history")
	var replacement_audit := history.retention_audit()
	_expect(replacement_audit.cache_aligned and replacement_audit.redo.command_count == 0 and replacement_audit.redo.snapshot_count == 0, "new edit clears redo commands and runtime snapshots together")
	history.undo()
	history.redo()
	var history_path := "user://edited-round-trip.json"
	_expect(history.current.save_path(history_path).is_empty(), "edited recipe saves")
	var edited_reopen := DiagramDocument.load_path(history_path)
	_expect(edited_reopen.ok and edited_reopen.document.to_json() == history.current.to_json(), "edited recipe reopens exactly")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(history_path))
	_expect(label_source != history.current.to_json(), "separate point and label commands retain distinct exact states")
	var edit_canvas := DiagramCanvas.new()
	edit_canvas.size = Vector2(800, 500)
	edit_canvas.set_document(planar)
	var object_record: Dictionary = planar.inspector_records()[1]
	var object_screen := edit_canvas.screen_position_for_record(object_record)
	_expect(edit_canvas.begin_edit_drag(object_screen), "canvas begins point drag from hit-tested record")
	var preview := edit_canvas.update_edit_drag(object_screen + Vector2(20, 0))
	_expect(preview.ok and edit_canvas.preview_record.id == "p2" and planar.to_json() == original_source, "drag preview is separate from accepted record")
	var right_neighbor_screen := edit_canvas.screen_position_for_record(planar.inspector_records()[2])
	preview = edit_canvas.update_edit_drag(right_neighbor_screen + Vector2(5, 0))
	_expect(not preview.ok and "strictly between" in preview.error and planar.to_json() == original_source, "invalid drag preview cannot reorder objects")
	edit_canvas.cancel_edit_preview()
	_expect(not edit_canvas.edit_dragging and edit_canvas.preview_record.is_empty(), "cancel clears draft without changing record")
	edit_canvas.free()
	var multi_source := multi.to_json()
	var itinerary_proposal := multi.with_curve_cuts("editable", [0, 6])
	_expect(itinerary_proposal.ok and itinerary_proposal.document.data.curves[1].cuts == [0, 6], "curve proposal preserves exact ordered cut visits")
	_expect(multi.to_json() == multi_source, "curve proposal does not mutate accepted document")
	var repeated_visit := multi.with_curve_cuts("editable", [0, 0])
	_expect(not repeated_visit.ok and "nonminimal" in repeated_visit.error, "consecutive repeated cut draft is rejected without simplification")
	var invalid_visit := multi.with_curve_cuts("editable", [0, "6"])
	_expect(not invalid_visit.ok, "noninteger cut draft is rejected")
	_expect(not multi.with_curve_cuts("missing", [0, 6]).ok and not braid.with_curve_cuts("editable", [0, 6]).ok, "unknown curve and braid edits are rejected")
	_expect(not multi.with_curve_cuts("editable", [0, 7]).ok, "out-of-range cut is rejected")
	var proposed_data: Dictionary = itinerary_proposal.document.to_dict()
	proposed_data.curves[1].cuts = [0]
	_expect(proposed_data == multi.to_dict(), "changing cuts preserves every other field including sibling curves")
	var loop_data := multi.to_dict()
	loop_data.curves = [{"id": "loopA", "kind": "loop", "cuts": [0, 6], "start_up": false}]
	var loop_document := DiagramDocument.parse(JSON.stringify(loop_data))
	var loop_edit: Dictionary = loop_document.document.with_curve_cuts("loopA", [0, 5])
	_expect(loop_edit.ok and loop_edit.document.data.curves[0].start_up == false, "loop itinerary editor preserves orientation")
	_expect(not loop_document.document.with_curve_cuts("loopA", [0, 5, 1]).ok, "odd loop draft is rejected without dropping a cut")
	_expect(not loop_document.document.with_curve_cuts("loopA", [0, 5, 1, 0]).ok, "cyclic cancellation in loop draft is rejected without simplification")
	var curve_history := DiagramEditHistory.new()
	curve_history.set_document(multi)
	var route_rejection := curve_history.set_curve_cuts("editable", [0, 5], PythonGeometryBridge.render)
	_expect(not route_rejection.ok and curve_history.current.to_json() == multi_source and not curve_history.can_undo(), "Python routing rejection preserves curve record and history")
	var itinerary_edit := curve_history.set_curve_cuts("editable", [0, 6], PythonGeometryBridge.render)
	_expect(itinerary_edit.ok and itinerary_edit.document.data.curves[1].cuts == [0, 6], "geometry-accepted itinerary becomes one command")
	var itinerary_source: String = curve_history.current.to_json()
	_expect(curve_history.undo().document.to_json() == multi_source, "curve undo restores exact initial itinerary")
	_expect(curve_history.redo().document.to_json() == itinerary_source, "curve redo restores exact accepted itinerary")
	var multi_path := "user://multi-curve-edited.json"
	_expect(curve_history.current.save_path(multi_path).is_empty(), "edited multi-curve recipe saves")
	var multi_reopen := DiagramDocument.load_path(multi_path)
	_expect(multi_reopen.ok and multi_reopen.document.to_json() == itinerary_source and PythonGeometryBridge.render(multi_reopen.document).ok, "edited multi-curve recipe reopens with exact publication geometry")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(multi_path))
	var inspector := CurveInspector.new()
	var editable_record: Dictionary = multi.inspector_records()[7]
	inspector.inspect(multi, editable_record)
	_expect(inspector.visible and inspector.curve_id == "editable" and inspector.draft_cuts == [0], "curve inspector exposes selected stable curve and accepted cuts")
	inspector.append_cut(6)
	inspector.append_cut(0)
	_expect(inspector.draft_cuts == [0, 6, 0], "curve inspector preserves ordered and repeated picks")
	inspector.append_cut(0)
	_expect("nonminimal" in inspector.warning_label.text and inspector.draft_cuts == [0, 6, 0, 0], "curve inspector warns without silently altering invalid draft")
	inspector.inspect(multi, multi.inspector_records()[6])
	inspector.inspect(multi, editable_record)
	_expect(inspector.draft_cuts == [0, 6, 0, 0], "draft survives selection changes")
	inspector.inspect(multi, multi.inspector_records()[0])
	_expect(not inspector.visible, "non-curve hides editor without deleting drafts")
	inspector.inspect(multi, editable_record)
	for i in 70:
		inspector.append_cut(i % 2)
	_expect(inspector.draft_cuts.size() == 64 and "limit" in inspector.warning_label.text, "interactive draft is bounded without trimming earlier visits")
	inspector._reset()
	_expect(inspector.draft_cuts == [0] and not inspector.drafts.has("editable"), "reset explicitly discards only selected curve draft")
	inspector.free()
	var cut_canvas := DiagramCanvas.new()
	cut_canvas.size = Vector2(900, 520)
	cut_canvas.set_document(multi)
	cut_canvas.select_record(editable_record)
	var cut_screen := cut_canvas.screen_position_for_cut(6)
	_expect(cut_canvas._hit_cut(cut_screen) == 6, "canvas hit-tests numbered cut exactly")
	_expect(cut_canvas._hit_cut(cut_screen + Vector2(0, 35)) == 6, "numbered cut label is also clickable")
	cut_canvas.zoom = 0.25
	var crowded_left := cut_canvas.screen_position_for_cut(1)
	var crowded_right := cut_canvas.screen_position_for_cut(2)
	_expect(cut_canvas._hit_cut(crowded_right) == 2, "crowded cut picking chooses nearest not first index")
	_expect(cut_canvas._hit_cut((crowded_left + crowded_right) / 2.0) == -1, "equidistant ambiguous cut pick is ignored")
	cut_canvas.zoom = 1.0
	var picked: Array[int] = []
	cut_canvas.cut_picked.connect(func(cut): picked.append(cut))
	var cut_event := InputEventMouseButton.new()
	cut_event.button_index = MOUSE_BUTTON_LEFT
	cut_event.pressed = true
	cut_event.position = cut_screen
	cut_canvas._gui_input(cut_event)
	_expect(picked == [6], "canvas emits cut picks in click order")
	cut_canvas.free()
	var outer_arc := {"id": "outerArc", "kind": "arc", "color": "#ff00d4",
		"cuts": [], "start": 0, "end": 7, "direction": "up",
		"start_side": null, "end_side": null}
	var added_arc := multi.with_added_curve(outer_arc)
	_expect(added_arc.ok and added_arc.document.data.curves.size() == 4, "new arc proposal appends one exact curve record")
	_expect(added_arc.ok and added_arc.document.data.curves[3] == outer_arc, "new arc preserves stable ID, magenta color, endpoints, orientation, and literal cuts")
	_expect(multi.to_json() == multi_source and multi.data.curves.size() == 3, "curve proposal does not mutate the accepted document")
	var duplicate_arc := outer_arc.duplicate(true); duplicate_arc.id = "left"
	_expect(not multi.with_added_curve(duplicate_arc).ok, "duplicate new stable curve ID is rejected")
	var invalid_arc := outer_arc.duplicate(true); invalid_arc.id = "bad id"
	_expect(not multi.with_added_curve(invalid_arc).ok, "unsafe new stable curve ID is rejected")
	invalid_arc = outer_arc.duplicate(true); invalid_arc.end = 0
	_expect(not multi.with_added_curve(invalid_arc).ok, "new arc with identical endpoints is rejected")
	invalid_arc = outer_arc.duplicate(true); invalid_arc.cuts = [0]
	_expect(not multi.with_added_curve(invalid_arc).ok, "new arc terminal cancellation is rejected without dropping the visit")
	_expect(not braid.with_added_curve(outer_arc).ok, "braid records cannot create planar curves")
	var creation_history := DiagramEditHistory.new()
	creation_history.set_document(multi)
	var narrow_arc := outer_arc.duplicate(true)
	narrow_arc.id = "narrowArc"; narrow_arc.start = 2; narrow_arc.end = 5; narrow_arc.direction = "default"
	var rejected_creation := creation_history.add_curve(narrow_arc, PythonGeometryBridge.render)
	_expect(not rejected_creation.ok and creation_history.current.to_json() == multi_source and not creation_history.can_undo(), "Python routing rejection preserves accepted record and creation history")
	var created_arc := creation_history.add_curve(outer_arc, PythonGeometryBridge.render)
	_expect(created_arc.ok and creation_history.undo_stack.size() == 1 and created_arc.selection.id == "outerArc", "Python-accepted arc creation is one selected-ID command")
	var created_arc_source: String = creation_history.current.to_json()
	var created_arc_geometry := PythonGeometryBridge.render(creation_history.current)
	_expect(created_arc_geometry.ok and created_arc_geometry.svg.begins_with("<svg") and "tikzpicture" in created_arc_geometry.tikz, "created arc has exact Python SVG and TikZ")
	_expect(creation_history.undo().document.to_json() == multi_source, "curve creation undo restores exact prior recipe")
	_expect(creation_history.redo().document.to_json() == created_arc_source, "curve creation redo restores exact appended recipe")
	var creation_path := "user://created-curve-round-trip.json"
	_expect(creation_history.current.save_path(creation_path).is_empty(), "created curve recipe saves")
	var creation_reopen := DiagramDocument.load_path(creation_path)
	var reopened_geometry := PythonGeometryBridge.render(creation_reopen.document) if creation_reopen.ok else {"ok": false}
	_expect(creation_reopen.ok and creation_reopen.document.to_json() == created_arc_source, "created curve recipe reopens exactly")
	_expect(reopened_geometry.ok and reopened_geometry.svg == created_arc_geometry.svg and reopened_geometry.tikz == created_arc_geometry.tikz, "save and reopen reproduce byte-identical publication exports")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(creation_path))
	var outer_loop := {"id": "outerLoop", "kind": "loop", "color": "#ff00d4",
		"cuts": [0, 6], "start_up": false}
	var added_loop := multi.with_added_curve(outer_loop)
	_expect(added_loop.ok and PythonGeometryBridge.render(added_loop.document).ok and added_loop.document.data.curves[3] == outer_loop, "new loop preserves stable ID, orientation, and ordered cuts through Python routing")
	var creator := CurveCreator.new()
	creator.configure(multi)
	creator.start("arc")
	_expect(creator.active and creator.draft.id == "arc1" and creator.draft.start == 0 and creator.draft.end == 7, "arc creator starts a bounded outer-endpoint draft with a fresh stable ID")
	_expect(creator.draft.color == "#ff00d4" and creator.draft.has("start_side") and creator.draft.has("end_side"), "arc creator makes color and rim-side fields explicit")
	creator.id_edit.text = "left"
	creator._id_changed("left")
	_expect("duplicate" in creator.warning_label.text.to_lower() and multi.to_json() == multi_source, "creator warns about duplicate ID without changing accepted data")
	creator.id_edit.text = "arcFresh"
	creator._id_changed("arcFresh")
	creator.append_cut(0)
	_expect(creator.draft.cuts == [0] and "terminal" in creator.warning_label.text.to_lower(), "creator retains an invalid literal cut and explains schema rejection")
	creator._clear_cuts()
	var emitted_specs: Array = []
	creator.create_requested.connect(func(spec): emitted_specs.append(spec))
	creator._create()
	_expect(emitted_specs.size() == 1 and emitted_specs[0].id == "arcFresh" and emitted_specs[0].cuts == [], "creator emits an exact defensive creation proposal")
	creator.start("loop")
	creator.append_cut(0)
	_expect("positive even" in creator.warning_label.text and creator.draft.cuts == [0], "loop creator retains incomplete ordered visit draft")
	creator.append_cut(6)
	creator.start_up_check.button_pressed = false
	creator._start_up_changed(false)
	_expect(creator.draft.cuts == [0, 6] and creator.draft.start_up == false and "strict schema" in creator.warning_label.text, "loop creator exposes exact orientation and an accepted-shape visit list")
	creator.cancel()
	_expect(not creator.active and creator.draft.is_empty(), "explicit cancel clears only the new-curve draft")
	creator.free()
	var reindex := RowReindex.adjacent(multi, "p1", 1)
	_expect(reindex.ok and reindex.old_order == ["p1", "p2", "p3", "p4", "p5", "p6"] and reindex.new_order == ["p2", "p1", "p3", "p4", "p5", "p6"], "row reindex proposes one explicit adjacent stable-ID swap")
	_expect(reindex.document.data.surface.objects[0].id == "p2" and reindex.document.data.surface.objects[0].x == -150.0 and reindex.document.data.surface.objects[1].id == "p1" and reindex.document.data.surface.objects[1].x == -90.0, "reindex moves identities between fixed ordered slots")
	_expect(reindex.document.data.curves == multi.data.curves, "reindex preserves every literal curve ID, endpoint, cut, and orientation field")
	_expect("curve left start endpoint 1: p1 -> p2" in reindex.impacts and "curve editable cut visit 1 at cut 0: outer-left | p1 -> outer-left | p2" in reindex.impacts, "proposal enumerates affected endpoint attachments and cut corridors")
	_expect("Endpoint and cut numbers remain literal" in RowReindex.preview_text(reindex), "reindex preview states its numbering policy")
	_expect(not RowReindex.adjacent(multi, "p1", -1).ok and not RowReindex.adjacent(multi, "missing", 1).ok, "row edges and unknown stable IDs are rejected")
	_expect(not multi.with_object_order(["p1", "p1", "p3", "p4", "p5", "p6"]).ok and not multi.with_object_order(["p2"]).ok, "duplicate and incomplete object orders are rejected")
	_expect(not braid.with_object_order([]).ok, "braid records cannot enter planar reindexing")
	var mixed_row_data := multi.to_dict()
	mixed_row_data.surface.objects[0].kind = "boundary"
	mixed_row_data.surface.objects[0].radius = 9.0
	var mixed_row: DiagramDocument = DiagramDocument.parse(JSON.stringify(mixed_row_data)).document
	var mixed_reindex: Dictionary = RowReindex.adjacent(mixed_row, "p1", 1)
	_expect(mixed_reindex.ok and mixed_reindex.document.data.surface.objects[1].id == "p1" and mixed_reindex.document.data.surface.objects[1].kind == "boundary" and mixed_reindex.document.data.surface.objects[1].radius == 9.0, "stable object kind and radius move with identity rather than the slot")
	var reindex_geometry := PythonGeometryBridge.render(reindex.document)
	_expect(reindex_geometry.ok and reindex_geometry.svg == multi_geometry.svg and reindex_geometry.tikz == multi_geometry.tikz, "point-identity reindex passes Python geometry and keeps exact publication output")
	var reindex_history := DiagramEditHistory.new()
	reindex_history.set_document(multi)
	var rejected_reindex := reindex_history.reindex_objects(reindex.new_order, "p1", func(_candidate): return {"ok": false, "error": "test rejection"})
	_expect(not rejected_reindex.ok and reindex_history.current.to_json() == multi_source and not reindex_history.can_undo(), "failed reindex validation preserves exact state and history")
	var accepted_reindex := reindex_history.reindex_objects(reindex.new_order, "p1", PythonGeometryBridge.render)
	_expect(accepted_reindex.ok and accepted_reindex.selection.id == "p1" and reindex_history.undo_stack.size() == 1, "validated reindex commits as one selected-ID command")
	_expect(reindex_history.undo().document.to_json() == multi_source and reindex_history.redo().document.to_json() == reindex.document.to_json(), "reindex undo and redo restore exact recipes")
	var recovery_history := DiagramEditHistory.new()
	recovery_history.set_document(multi)
	var recovered_edit := recovery_history.set_curve_cuts("editable", [0, 6], PythonGeometryBridge.render)
	_expect(recovered_edit.ok, "recovery fixture accepts an exact curve command")
	var recovery_after: String = recovery_history.current.to_json()
	recovery_history.undo()
	var recovery_drafts := {"editable": [0, 0], "left": [1, 2, 1]}
	var recovery_selection := {"kind": "curve", "id": "editable", "index": 1}
	var recovery_view := WorkspaceViewState.defaults(recovery_history.current)
	recovery_view.camera = {"zoom": 1.75, "pan": [123.5, -44.25]}
	recovery_view.panels = {"records": true, "source": true, "move_points": false}
	var encoded_recovery := WorkspaceRecovery.encode(multi_source, recovery_history,
		recovery_drafts, recovery_selection, recovery_view)
	_expect(encoded_recovery.ok and encoded_recovery.text.length() > 0, "bounded recovery envelope encodes accepted state, history, drafts, and separate view state")
	var encoded_recovery_raw: Dictionary = JSON.parse_string(encoded_recovery.text)
	_expect(encoded_recovery_raw.version == 3 and encoded_recovery_raw.history.format == DiagramEditHistory.COMPACT_STATE_FORMAT and encoded_recovery_raw.history.documents.size() == 2, "new recovery writes version 3 with deduplicated command endpoints and a native view envelope")
	_expect(encoded_recovery_raw.view.camera.zoom == 1.75 and encoded_recovery_raw.view.camera.pan == [123.5, -44.25] and not encoded_recovery_raw.history.has("view"), "view state stays outside every mathematical history document")
	var excess_recovery_history: Dictionary = encoded_recovery_raw.history.duplicate(true)
	excess_recovery_history.documents.append(braid.to_json())
	_expect(not DiagramEditHistory.new().restore_compact_state(excess_recovery_history).ok, "compact history rejects unreferenced document slots")
	var parsed_recovery := WorkspaceRecovery.parse(encoded_recovery.text)
	_expect(parsed_recovery.ok and parsed_recovery.recovery_version == 3 and parsed_recovery.baseline_source == multi_source, "recovery envelope retains exact normalized baseline and version")
	_expect(parsed_recovery.ok and parsed_recovery.drafts == recovery_drafts, "recovery retains literal invalid drafts without simplifying them")
	_expect(parsed_recovery.ok and parsed_recovery.selection == recovery_selection, "recovery retains stable record selection")
	_expect(parsed_recovery.ok and parsed_recovery.view_state == recovery_view, "recovery retains bounded camera and panel state without extending DiagramDocument")
	var restored_history := DiagramEditHistory.new()
	var restore_result := restored_history.restore_state(parsed_recovery.history_state)
	_expect(restore_result.ok and restored_history.current.to_json() == multi_source and restored_history.can_redo(), "recovery restores current record and redo stack")
	var restored_audit := restored_history.retention_audit()
	_expect(restored_audit.cache_aligned and restored_audit.totals.snapshot_count == 1 and restored_audit.totals.snapshot_source_bytes == 0, "recovery rebuilds document-only runtime snapshots without changing serialized history")
	_expect(restored_history.redo().document.to_json() == recovery_after and restored_history.can_undo(), "restored redo reproduces the exact accepted itinerary")
	_expect(restored_history.undo().document.to_json() == multi_source, "restored undo reproduces the exact prior recipe")
	var legacy_recovery := {
		"format": WorkspaceRecovery.FORMAT,
		"version": WorkspaceRecovery.LEGACY_VERSION,
		"baseline": multi_source,
		"history": recovery_history.to_state(),
		"drafts": recovery_drafts,
		"selection": recovery_selection,
	}
	var parsed_legacy_recovery := WorkspaceRecovery.parse(JSON.stringify(legacy_recovery))
	_expect(parsed_legacy_recovery.ok and parsed_legacy_recovery.recovery_version == 1 and parsed_legacy_recovery.history_state == parsed_recovery.history_state, "version-1 recovery remains readable and normalizes to the exact public history state")
	_expect(parsed_legacy_recovery.view_state == WorkspaceViewState.defaults(recovery_history.current), "version-1 recovery receives deterministic default view state")
	var compact_recovery: Dictionary = encoded_recovery_raw.duplicate(true)
	compact_recovery.version = WorkspaceRecovery.COMPACT_VERSION
	compact_recovery.erase("view")
	var parsed_compact_recovery := WorkspaceRecovery.parse(JSON.stringify(compact_recovery))
	_expect(parsed_compact_recovery.ok and parsed_compact_recovery.recovery_version == 2 and parsed_compact_recovery.view_state == WorkspaceViewState.defaults(recovery_history.current), "version-2 compact recovery remains readable with deterministic default view state")
	var future_recovery: Dictionary = JSON.parse_string(encoded_recovery.text)
	future_recovery.version = 4
	_expect(not WorkspaceRecovery.parse(JSON.stringify(future_recovery)).ok, "future recovery version is rejected")
	var duplicate_recovery: String = encoded_recovery.text.replace("\"version\": 3,", "\"version\": 3,\n\t\"version\": 3,")
	_expect(not WorkspaceRecovery.parse(duplicate_recovery).ok, "duplicate recovery field is rejected")
	var unknown_recovery: Dictionary = JSON.parse_string(encoded_recovery.text)
	unknown_recovery.camera = {"zoom": 2}
	_expect(not WorkspaceRecovery.parse(JSON.stringify(unknown_recovery)).ok, "unknown recovery field is rejected rather than merged into mathematical data")
	var invalid_view: Dictionary = JSON.parse_string(encoded_recovery.text)
	invalid_view.view.camera.zoom = 9.0
	_expect(not WorkspaceRecovery.parse(JSON.stringify(invalid_view)).ok, "out-of-range native camera state is rejected without affecting mathematical recovery")
	var unknown_draft: Dictionary = JSON.parse_string(encoded_recovery.text)
	unknown_draft.drafts = {"missing": [0]}
	_expect(not WorkspaceRecovery.parse(JSON.stringify(unknown_draft)).ok, "recovery draft for unknown stable curve ID is rejected")
	var discontinuous: Dictionary = JSON.parse_string(encoded_recovery.text)
	discontinuous.history.redo[0].before = discontinuous.history.redo[0].after
	_expect(not WorkspaceRecovery.parse(JSON.stringify(discontinuous)).ok, "noncontiguous recovery history is rejected")
	var overfull_state := recovery_history.to_state()
	var repeated_command: Dictionary = overfull_state.redo[0].duplicate(true)
	overfull_state.undo = []
	overfull_state.redo = []
	for index in 101: overfull_state.redo.append(repeated_command.duplicate(true))
	_expect(not DiagramEditHistory.new().restore_state(overfull_state).ok, "recovery rejects more than 100 total undo and redo commands before retaining snapshots")
	var oversized_recovery := " ".repeat(WorkspaceRecovery.MAX_BYTES) + "{}"
	_expect(not WorkspaceRecovery.parse(oversized_recovery).ok, "oversized recovery envelope is rejected before use")
	WorkspaceRecovery.clear_file()
	var legacy_file := FileAccess.open(WorkspaceRecovery.LEGACY_PATH, FileAccess.WRITE)
	legacy_file.store_string(JSON.stringify(legacy_recovery))
	legacy_file.close()
	var loaded_legacy_recovery := WorkspaceRecovery.load_file()
	_expect(loaded_legacy_recovery.ok and loaded_legacy_recovery.found and loaded_legacy_recovery.recovery_version == 1 and loaded_legacy_recovery.generation == 0 and loaded_legacy_recovery.slot_source == "legacy", "loader falls back to the existing version-1 recovery path")
	var save_recovery_error := WorkspaceRecovery.save_file(multi_source, recovery_history, recovery_drafts, recovery_selection, recovery_view)
	var loaded_recovery := WorkspaceRecovery.load_file()
	_expect(save_recovery_error.is_empty() and loaded_recovery.ok and loaded_recovery.found and loaded_recovery.recovery_version == 3 and loaded_recovery.generation == 1 and loaded_recovery.slot_source == "primary" and not FileAccess.file_exists(WorkspaceRecovery.LEGACY_PATH), "version-3 recovery writes a generation-1 primary and retires the legacy path")
	_expect(loaded_recovery.drafts == recovery_drafts and loaded_recovery.history_state == parsed_recovery.history_state, "disk recovery round trip retains drafts and command history exactly")
	_expect(loaded_recovery.view_state == recovery_view, "disk recovery round trip retains the separate native view envelope")
	var migrated_backup := WorkspaceRecovery.parse_slot(FileAccess.get_file_as_string(WorkspaceRecovery.BACKUP_PATH))
	_expect(migrated_backup.ok and migrated_backup.generation == 0 and migrated_backup.recovery_version == 1, "version-1 migration preserves the validated legacy record as generation-0 last-known-good data")
	_expect(recovery_history.redo().ok and recovery_history.current.to_json() == recovery_after, "recovery slot fixture advances to a distinct accepted generation")
	var second_save_error := WorkspaceRecovery.save_file(multi_source, recovery_history, recovery_drafts, recovery_selection)
	var second_loaded := WorkspaceRecovery.load_file()
	_expect(second_save_error.is_empty() and second_loaded.ok and second_loaded.generation == 2 and second_loaded.slot_source == "primary" and DiagramDocument.parse(second_loaded.history_state.current).document.to_json() == recovery_after, "second checkpoint advances the primary generation and exact current record")
	var rotated_backup := WorkspaceRecovery.parse_slot(FileAccess.get_file_as_string(WorkspaceRecovery.BACKUP_PATH))
	_expect(rotated_backup.ok and rotated_backup.generation == 1 and DiagramDocument.parse(rotated_backup.history_state.current).document.to_json() == multi_source, "second checkpoint rotates the prior primary into last-known-good storage")
	var truncated_primary := FileAccess.open(WorkspaceRecovery.PATH, FileAccess.WRITE)
	truncated_primary.store_string("{\"format\":")
	truncated_primary.close()
	var truncation_fallback := WorkspaceRecovery.load_file()
	_expect(truncation_fallback.ok and truncation_fallback.recovered_from_backup and truncation_fallback.generation == 1 and DiagramDocument.parse(truncation_fallback.history_state.current).document.to_json() == multi_source, "truncated primary deterministically falls back to the exact prior generation")
	_expect(WorkspaceRecovery.save_file(multi_source, recovery_history, recovery_drafts, recovery_selection).is_empty(), "saving after truncation repairs the primary without discarding last-known-good data")
	var inflated_generation: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(WorkspaceRecovery.PATH))
	inflated_generation.generation = 999
	var inflated_generation_file := FileAccess.open(WorkspaceRecovery.PATH, FileAccess.WRITE)
	inflated_generation_file.store_string(JSON.stringify(inflated_generation))
	inflated_generation_file.close()
	var generation_fallback := WorkspaceRecovery.load_file()
	_expect(generation_fallback.ok and generation_fallback.recovered_from_backup and generation_fallback.generation == 1, "generation metadata is checksummed and cannot make a corrupted primary outrank last-known-good data")
	_expect(WorkspaceRecovery.save_file(multi_source, recovery_history, recovery_drafts, recovery_selection).is_empty(), "saving after generation corruption installs a new validated primary")
	var corrupt_primary: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(WorkspaceRecovery.PATH))
	corrupt_primary.sha256 = "0".repeat(64)
	var corrupt_primary_file := FileAccess.open(WorkspaceRecovery.PATH, FileAccess.WRITE)
	corrupt_primary_file.store_string(JSON.stringify(corrupt_primary))
	corrupt_primary_file.close()
	var checksum_fallback := WorkspaceRecovery.load_file()
	_expect(checksum_fallback.ok and checksum_fallback.recovered_from_backup and checksum_fallback.generation == 1, "checksum corruption cannot outrank the validated last-known-good slot")
	_expect(WorkspaceRecovery.save_file(multi_source, recovery_history, recovery_drafts, recovery_selection).is_empty(), "saving after checksum corruption installs a new validated primary")
	var primary_payload: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(WorkspaceRecovery.PATH)).payload
	var newer_backup := WorkspaceRecovery._encode_slot(primary_payload, 3)
	var newer_backup_file := FileAccess.open(WorkspaceRecovery.BACKUP_PATH, FileAccess.WRITE)
	newer_backup_file.store_string(newer_backup.text)
	newer_backup_file.close()
	var newest_fallback := WorkspaceRecovery.load_file()
	_expect(newest_fallback.ok and newest_fallback.recovered_from_backup and newest_fallback.generation == 3, "newest valid generation wins even when it occupies the last-known-good path")
	_expect(WorkspaceRecovery.save_file(multi_source, recovery_history, recovery_drafts, recovery_selection).is_empty() and WorkspaceRecovery.load_file().generation == 4, "checkpoint after fallback continues from the newest trusted generation")
	var broken_primary_file := FileAccess.open(WorkspaceRecovery.PATH, FileAccess.WRITE)
	broken_primary_file.store_string("{")
	broken_primary_file.close()
	var broken_backup_file := FileAccess.open(WorkspaceRecovery.BACKUP_PATH, FileAccess.WRITE)
	broken_backup_file.store_string("{")
	broken_backup_file.close()
	var no_valid_slot := WorkspaceRecovery.load_file()
	_expect(not no_valid_slot.ok and no_valid_slot.found and "No valid workspace recovery slot" in no_valid_slot.error, "two invalid slots are reported instead of restoring untrusted data")
	_expect(WorkspaceRecovery.save_file(multi_source, recovery_history, recovery_drafts, recovery_selection).is_empty() and WorkspaceRecovery.load_file().generation == 1 and not FileAccess.file_exists(WorkspaceRecovery.BACKUP_PATH), "fresh checkpoint replaces invalid slots and removes the stale backup")
	WorkspaceRecovery.clear_file()
	var raw_v2_file := FileAccess.open(WorkspaceRecovery.PATH, FileAccess.WRITE)
	raw_v2_file.store_string(JSON.stringify(compact_recovery))
	raw_v2_file.close()
	var raw_v2_loaded := WorkspaceRecovery.load_file()
	_expect(raw_v2_loaded.ok and raw_v2_loaded.generation == 0 and raw_v2_loaded.slot_version == 0 and raw_v2_loaded.recovery_version == 2, "unwrapped version-2 checkpoint from the previous release remains readable")
	_expect(WorkspaceRecovery.save_file(multi_source, recovery_history, recovery_drafts, recovery_selection).is_empty() and WorkspaceRecovery.parse_slot(FileAccess.get_file_as_string(WorkspaceRecovery.BACKUP_PATH)).recovery_version == 2, "first guarded save migrates an unwrapped version-2 checkpoint into last-known-good storage")
	WorkspaceRecovery.clear_file()
	_expect(not FileAccess.file_exists(WorkspaceRecovery.PATH) and not FileAccess.file_exists(WorkspaceRecovery.BACKUP_PATH) and not FileAccess.file_exists(WorkspaceRecovery.LEGACY_PATH) and not FileAccess.file_exists(WorkspaceRecovery.PATH + ".tmp") and not FileAccess.file_exists(WorkspaceRecovery.BACKUP_PATH + ".tmp"), "explicit recovery discard removes primary, last-known-good, legacy, and temporary files")
	var scene := load("res://scenes/studio.tscn")
	_expect(scene is PackedScene, "main scene loads")
	if scene is PackedScene:
		var instance: Node = scene.instantiate()
		_expect(instance != null, "main scene instantiates")
		instance.free()

func _fixture(path: String) -> DiagramDocument:
	var result := DiagramDocument.load_path(path)
	_expect(result.ok, path + " parses: " + result.get("error", ""))
	return result.document if result.ok else null

func _reject(text: String, label: String) -> void:
	var result := DiagramDocument.parse(text)
	_expect(not result.ok, label + " rejected")

func _expect(condition: bool, label: String) -> void:
	assertions += 1
	if not condition:
		failures += 1
		printerr("FAIL: " + label)
