extends SceneTree

var failures := 0
var assertions := 0

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	# The dummy display defaults to 64x64; test an actual desktop workspace.
	root.size = Vector2i(1280, 800)
	WorkspaceRecovery.clear_file()
	var packed := load("res://scenes/studio.tscn") as PackedScene
	_check(packed != null, "studio scene loads")
	if packed == null:
		_finish()
		return
	var studio := packed.instantiate()
	root.add_child(studio)
	await process_frame
	await process_frame
	_check(studio.document != null, "ready opens initial document")
	_check(studio.document.data.kind == "planar", "initial fixture is planar")
	_check(studio.record_list.item_count == 6, "planar inspector shows four objects, curve, and label")
	_check(studio.canvas.document.to_json() == studio.document.to_json(), "canvas receives same immutable record")
	_check(studio.geometry_result.ok, "planar fixture has exact Python geometry")
	_check(not studio.svg_button.disabled and not studio.tikz_button.disabled, "publication exports are enabled after exact render")
	var planar_before: String = studio.document.to_json()
	studio.curve_creator.start("arc")
	var initial_creation_recovery := WorkspaceRecovery.load_file()
	_check(initial_creation_recovery.ok and initial_creation_recovery.found and initial_creation_recovery.creation_state.active and initial_creation_recovery.creation_state.draft == studio.curve_creator.draft and studio.document.to_json() == planar_before, "starting a new curve immediately checkpoints its separate literal draft")
	studio.curve_creator.cancel()
	_check(not studio._has_unsaved_work() and not WorkspaceRecovery.load_file().found and studio.document.to_json() == planar_before, "explicit creation cancel removes its clean-workspace recovery without touching mathematical JSON")
	studio.record_list.select(4)
	studio.record_list.item_selected.emit(4)
	_check(studio.canvas.selected_record.id == "arc1", "planar inspector selects stable curve ID")
	_check(studio.document.to_json() == planar_before, "selection does not change planar record")
	studio.export_kind = "svg"
	var export_path := "user://ui-smoke.svg"
	studio._save_export(export_path)
	var exported := FileAccess.get_file_as_string(export_path)
	_check(exported == studio.geometry_result.svg and exported.begins_with("<svg"), "Godot saves exact bridge SVG without regeneration")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(export_path))
	studio.export_kind = "tikz"
	export_path = "user://ui-smoke.tikz"
	studio._save_export(export_path)
	exported = FileAccess.get_file_as_string(export_path)
	_check(exported == studio.geometry_result.tikz and "tikzpicture" in exported, "Godot saves exact bridge TikZ without regeneration")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(export_path))
	studio.canvas.zoom_at(studio.canvas.size / 2.0, 1.2)
	studio.canvas.pan = Vector2(14, -6)
	var edit_zoom: float = studio.canvas.zoom
	var edit_pan: Vector2 = studio.canvas.pan
	var object_record: Dictionary = studio.document.inspector_records()[1]
	var point_start: Vector2 = studio.canvas.screen_position_for_record(object_record)
	_check(studio.canvas.begin_edit_drag(point_start), "live canvas hit-tests point for editing")
	var preview: Dictionary = studio.canvas.update_edit_drag(point_start + Vector2(20, 0))
	_check(preview.ok and studio.document.to_json() == planar_before, "live drag is a non-mutating preview")
	studio.canvas.finish_edit_drag(point_start + Vector2(20, 0))
	var planar_edited: String = studio.document.to_json()
	_check(planar_edited != planar_before and studio.document.data.surface.objects[1].id == "p2", "release commits accepted point move with stable ID")
	_check(studio.document.data.curves[0].cuts == [] and studio.document.data.curves[0].start == 1 and studio.document.data.curves[0].end == 3, "point edit preserves endpoint and cut records")
	_check(studio.geometry_result.ok and not studio.undo_button.disabled, "accepted edit has exact geometry and enables undo")
	_check(studio.canvas.zoom == edit_zoom and studio.canvas.pan == edit_pan, "accepted edit preserves separate camera state")
	studio._undo()
	_check(studio.document.to_json() == planar_before and not studio.redo_button.disabled, "UI undo restores exact original recipe")
	studio._redo()
	_check(studio.document.to_json() == planar_edited and not studio.undo_button.disabled, "UI redo restores exact edited recipe")
	object_record = studio.document.inspector_records()[1]
	point_start = studio.canvas.screen_position_for_record(object_record)
	var neighbor_position: Vector2 = studio.canvas.screen_position_for_record(studio.document.inspector_records()[2])
	_check(studio.canvas.begin_edit_drag(point_start), "second point drag begins")
	preview = studio.canvas.update_edit_drag(neighbor_position + Vector2(5, 0))
	_check(not preview.ok and studio.document.to_json() == planar_edited, "cross-neighbor drag remains a rejected preview")
	studio.canvas.finish_edit_drag(neighbor_position + Vector2(5, 0))
	_check(studio.document.to_json() == planar_edited and "strictly between" in studio.status_label.text, "rejected release preserves accepted point state")
	var label_record: Dictionary = studio.document.inspector_records()[-1]
	var label_start: Vector2 = studio.canvas.screen_position_for_record(label_record)
	_check(studio.canvas.begin_edit_drag(label_start), "live canvas hit-tests label for editing")
	studio.canvas.finish_edit_drag(label_start + Vector2(12, -10))
	_check(studio.document.data.labels[0].id == "label1" and studio.document.to_json() != planar_edited, "label drag commits as a separate command with stable ID")
	studio.record_list.item_selected.emit(4)
	studio.curve_inspector.append_cut(0)
	var guarded_source: String = studio.document.to_json()
	var guarded_history_size: int = studio.history.undo_stack.size()
	_check(not studio._request_close() and studio.pending_description == "close Studio", "close waits for explicit discard when recoverable work exists")
	studio._cancel_pending_action()
	_check(studio.document.to_json() == guarded_source and studio.curve_inspector.draft_cuts == [0], "cancelled close leaves accepted record and draft intact")
	studio._open_resource("res://fixtures/multi-curve-v1.json")
	_check(studio.document.to_json() == guarded_source and studio.pending_action.is_valid(), "fixture replacement waits for explicit discard when accepted edits or drafts exist")
	studio._cancel_pending_action()
	_check(studio.document.to_json() == guarded_source and studio.history.undo_stack.size() == guarded_history_size and studio.curve_inspector.draft_cuts == [0], "cancel preserves accepted record, exact history, and rejected draft")
	studio._open_resource("res://fixtures/multi-curve-v1.json")
	studio._discard_and_continue()
	await process_frame
	_check(studio.document.data.curves.size() == 3 and studio.record_list.item_count == 10, "multi-curve fixture opens with every curve in inspector")
	_check(not studio._has_unsaved_work() and not FileAccess.file_exists(WorkspaceRecovery.PATH), "confirmed successful replacement starts a clean workspace and clears old recovery")
	studio.record_list.item_selected.emit(7)
	_check(studio.curve_inspector.visible and studio.curve_inspector.curve_id == "editable", "selected curve opens cut editor by stable ID")
	var multi_before: String = studio.document.to_json()
	var svg_before: String = studio.geometry_result.svg
	var tikz_before: String = studio.geometry_result.tikz
	studio.curve_inspector.append_cut(5)
	studio.curve_inspector._apply()
	_check(studio.document.to_json() == multi_before and not studio.history.can_undo(), "unroutable itinerary preserves accepted recipe and history")
	_check(studio.geometry_result.svg == svg_before and studio.geometry_result.tikz == tikz_before, "rejected route preserves exact publication outputs")
	_check(studio.curve_inspector.draft_cuts == [0, 5] and "rejected" in studio.status_label.text, "rejected cuts remain available with error")
	_check("[draft]" in studio.record_list.get_item_text(7), "inspector marks the stable curve with pending input")
	studio.record_list.item_selected.emit(6)
	studio.curve_inspector.append_cut(1)
	studio.record_list.item_selected.emit(7)
	_check(studio.curve_inspector.draft_cuts == [0, 5], "switching curves recovers rejected draft by stable ID")
	studio._open_result({"ok": false, "error": "malformed file"}, "bad.json")
	_check(studio.curve_inspector.draft_cuts == [0, 5] and studio.document.to_json() == multi_before, "failed open preserves drafts as well as accepted state")
	studio.record_list.item_selected.emit(0)
	_check(studio.row_reindex_panel.visible and studio.reindex_left_button.disabled and not studio.reindex_right_button.disabled, "selected edge object exposes only the valid explicit reindex direction")
	var drafts_before_reindex: Dictionary = studio.curve_inspector.drafts.duplicate(true)
	var recovery_before_reindex: String = FileAccess.get_file_as_string(WorkspaceRecovery.PATH)
	var configured_python := OS.get_environment("SURFACE_DIAGRAMS_PYTHON")
	OS.set_environment("SURFACE_DIAGRAMS_PYTHON", "/definitely-missing-reindex-python")
	studio._request_reindex(1)
	OS.set_environment("SURFACE_DIAGRAMS_PYTHON", configured_python)
	_check(studio.pending_reindex.is_empty() and studio.document.to_json() == multi_before and studio.curve_inspector.drafts == drafts_before_reindex and FileAccess.get_file_as_string(WorkspaceRecovery.PATH) == recovery_before_reindex, "failed reindex geometry preserves accepted state, recovery, and drafts")
	studio._request_reindex(1)
	_check(not studio.pending_reindex.is_empty() and studio.document.to_json() == multi_before and not studio.history.can_undo(), "validated reindex remains a non-mutating proposal until confirmation")
	_check("curve left start endpoint 1: p1 -> p2" in studio.reindex_preview.text and "curve editable cut visit 1 at cut 0" in studio.reindex_preview.text, "confirmation preview lists affected endpoint and cut semantics")
	studio._cancel_reindex()
	_check(studio.document.to_json() == multi_before and studio.curve_inspector.drafts == drafts_before_reindex and not studio.history.can_undo() and FileAccess.get_file_as_string(WorkspaceRecovery.PATH) == recovery_before_reindex, "reindex cancel preserves exact record, history, recovery, and every draft")
	studio._request_reindex(1)
	studio._confirm_reindex()
	var reindexed_source: String = studio.document.to_json()
	_check(studio.document.data.surface.objects[0].id == "p2" and studio.document.data.surface.objects[1].id == "p1", "confirmed reindex moves stable IDs between fixed horizontal slots")
	_check(studio.document.data.curves == DiagramDocument.parse(multi_before).document.data.curves and studio.curve_inspector.drafts == drafts_before_reindex, "confirmed reindex preserves literal curve recipes and pending drafts")
	_check(studio.history.undo_stack.size() == 1 and studio.geometry_result.ok and "one command" in studio.status_label.text, "confirmed reindex is one Python-validated command")
	studio._undo()
	_check(studio.document.to_json() == multi_before and studio.curve_inspector.drafts == drafts_before_reindex and studio.history.can_redo(), "reindex undo restores exact source without deleting drafts")
	studio._redo()
	_check(studio.document.to_json() == reindexed_source and studio.curve_inspector.drafts == drafts_before_reindex, "reindex redo restores exact slot assignment")
	studio._undo()
	studio._canvas_edit_commit("label", "caption", Vector2(1, -85))
	_check(studio.curve_inspector.drafts["editable"] == [0, 5] and not studio.curve_inspector.visible, "non-curve command retains hidden curve drafts")
	_check("[draft]" in studio.record_list.get_item_text(7), "draft marker survives non-curve presentation refresh")
	studio.canvas.zoom = 1.75
	studio.canvas.pan = Vector2(123.5, -44.25)
	studio.showing_records = true
	studio.source_view.visible = true
	studio.move_button.set_pressed_no_signal(true)
	studio.canvas.touch_move_enabled = true
	studio._persist_recovery()
	var recovery_on_disk := WorkspaceRecovery.load_file()
	_check(recovery_on_disk.ok and recovery_on_disk.found and recovery_on_disk.drafts.size() == 2, "accepted edit and every curve draft are written to separate bounded recovery")
	_check(recovery_on_disk.view_state.camera.zoom == 1.75 and recovery_on_disk.view_state.camera.pan == [123.5, -44.25] and recovery_on_disk.view_state.panels.records and recovery_on_disk.view_state.panels.source and recovery_on_disk.view_state.panels.move_points, "recovery stores bounded editor camera and panel state outside mathematical JSON")
	var restarted = packed.instantiate()
	root.add_child(restarted)
	await process_frame
	_check(not restarted.startup_recovery.is_empty() and restarted.document.data.title == "Generic planar import fixture", "restart offers recovery without silently replacing the startup fixture")
	_check(restarted._restore_startup_recovery(), "explicit restore accepts the validated recovery envelope")
	_check(restarted.document.to_json() == studio.document.to_json() and restarted.curve_inspector.drafts == studio.curve_inspector.drafts, "restart restores accepted record and all drafts exactly")
	_check(restarted.canvas.selected_record.kind == "label" and restarted.canvas.selected_record.id == "caption", "restart restores stable-ID selection separately from mathematical data")
	_check(restarted.canvas.zoom == 1.75 and restarted.canvas.pan == Vector2(123.5, -44.25) and restarted.showing_records and restarted.source_view.visible and restarted.move_button.button_pressed, "restart restores camera and panel state from the separate native envelope")
	_check(restarted.history.undo_stack.size() == studio.history.undo_stack.size() and restarted.history.can_undo(), "restart restores exact command history")
	restarted._undo()
	_check(restarted.document.to_json() == multi_before and restarted.curve_inspector.drafts["editable"] == [0, 5], "recovered undo works without erasing rejected drafts")
	restarted.queue_free()
	await process_frame
	studio._undo()
	studio.record_list.item_selected.emit(7)
	_check(studio.document.to_json() == multi_before and studio.curve_inspector.draft_cuts == [0, 5], "undo of another edit preserves the rejected itinerary")
	studio.canvas.pan = Vector2(11, 17)
	studio.canvas.zoom = 1.1
	studio.curve_inspector._remove_last()
	studio.curve_inspector.append_cut(6)
	studio.curve_inspector._apply()
	var multi_after: String = studio.document.to_json()
	_check(multi_after != multi_before and studio.document.data.curves[1].cuts == [0, 6], "cut apply commits literal ordered itinerary")
	_check(studio.geometry_result.ok and studio.history.undo_stack.size() == 1, "accepted itinerary rendered and stored as one undo command")
	_check(studio.canvas.pan == Vector2(11, 17) and studio.canvas.zoom == 1.1, "itinerary command preserves camera")
	_check(studio.curve_inspector.drafts.has("left") and not studio.curve_inspector.drafts.has("editable"), "apply consumes only its own draft")
	_check("[draft]" in studio.record_list.get_item_text(6) and "[draft]" not in studio.record_list.get_item_text(7), "draft markers refresh after accepted command")
	var svg_after: String = studio.geometry_result.svg
	var tikz_after: String = studio.geometry_result.tikz
	var pick := InputEventMouseButton.new()
	pick.button_index = MOUSE_BUTTON_LEFT
	pick.pressed = true
	pick.position = studio.canvas.screen_position_for_cut(0)
	studio.canvas._gui_input(pick)
	_check(studio.curve_inspector.draft_cuts == [0, 6, 0] and studio.document.to_json() == multi_after, "canvas cut click appends exact visit without changing accepted data")
	studio._save_path("user://ui-multi.json")
	_check("NOT in this file" in studio.status_label.text, "save explains that unapplied drafts are excluded")
	_check(DiagramDocument.load_path("user://ui-multi.json").document.to_json() == multi_after, "saving with a draft writes only exact accepted recipe")
	_check(studio._has_unsaved_work() and WorkspaceRecovery.load_file().found, "saving accepted JSON keeps unapplied drafts recoverable and visibly unsaved")
	studio.curve_inspector._reset()
	studio._undo()
	_check(studio.document.to_json() == multi_before and studio.curve_inspector.draft_cuts == [0], "itinerary UI undo restores accepted recipe and inspector")
	_check(studio.geometry_result.svg == svg_before and studio.geometry_result.tikz == tikz_before, "undo regenerates byte-identical publication outputs")
	studio._redo()
	_check(studio.document.to_json() == multi_after and studio.curve_inspector.draft_cuts == [0, 6], "itinerary UI redo restores accepted recipe and inspector")
	_check(studio.geometry_result.svg == svg_after and studio.geometry_result.tikz == tikz_after, "redo regenerates byte-identical publication outputs")
	studio._open_path("user://ui-multi.json")
	_check(studio.document.to_json() == multi_after and studio.curve_inspector.drafts.is_empty(), "reopen keeps exact recipe with fresh session drafts")
	_check(studio.geometry_result.svg == svg_after and studio.geometry_result.tikz == tikz_after, "save/reopen retains publication output exactly")
	DirAccess.remove_absolute(ProjectSettings.globalize_path("user://ui-multi.json"))
	studio.record_list.item_selected.emit(6)
	studio.curve_inspector.append_cut(1)
	var sibling_drafts: Dictionary = studio.curve_inspector.drafts.duplicate(true)
	studio.record_list.item_selected.emit(0)
	studio.curve_creator.start("arc")
	_check(studio.curve_creator.active and studio.curve_creator.draft.start == 0 and studio.curve_creator.draft.end == 7, "live creator begins an in-memory arc draft with explicit outer endpoints")
	var new_curve_pick := InputEventMouseButton.new()
	new_curve_pick.button_index = MOUSE_BUTTON_LEFT
	new_curve_pick.pressed = true
	new_curve_pick.position = studio.canvas.screen_position_for_cut(0)
	studio.canvas._gui_input(new_curve_pick)
	_check(studio.curve_creator.draft.cuts == [0] and studio.canvas.curve_draft_cuts == [0] and studio.canvas.pick_for_new_curve, "creation cut picking works while a planar object is selected and shows numbered draft visit")
	studio.curve_creator._clear_cuts()
	_check(studio._has_unsaved_work(), "new-curve draft participates in unsaved-work protection")
	studio.curve_creator.id_edit.text = "left"
	studio.curve_creator._id_changed("left")
	var creation_before: String = studio.document.to_json()
	studio.curve_creator._create()
	_check(studio.document.to_json() == creation_before and not studio.history.can_undo() and studio.curve_creator.active, "duplicate-ID schema rejection retains creation draft and accepted record")
	_check("rejected" in studio.status_label.text and studio.curve_inspector.drafts == sibling_drafts, "schema rejection is visible and preserves every existing curve draft")
	studio.curve_creator.id_edit.text = "narrowArc"
	studio.curve_creator._id_changed("narrowArc")
	studio.curve_creator.start_spin.value = 2
	studio.curve_creator.end_spin.value = 5
	studio.curve_creator._start_changed(2)
	studio.curve_creator._end_changed(5)
	var recovery_before_creation_failure: String = FileAccess.get_file_as_string(WorkspaceRecovery.PATH)
	studio.curve_creator._create()
	_check(studio.document.to_json() == creation_before and not studio.history.can_undo() and studio.curve_creator.draft.id == "narrowArc", "Python routing rejection leaves narrow arc input available")
	_check(studio.curve_inspector.drafts == sibling_drafts and FileAccess.get_file_as_string(WorkspaceRecovery.PATH) == recovery_before_creation_failure, "routing rejection preserves other drafts and the last accepted recovery checkpoint")
	var rejected_creation_recovery := WorkspaceRecovery.load_file()
	_check(rejected_creation_recovery.ok and rejected_creation_recovery.creation_state.active and rejected_creation_recovery.creation_state.draft == studio.curve_creator.draft, "recovery checkpoints the complete rejected new-curve draft without simplifying it")
	var draft_restarted = packed.instantiate()
	root.add_child(draft_restarted)
	await process_frame
	_check(draft_restarted._restore_startup_recovery() and draft_restarted.document.to_json() == creation_before, "restart explicitly restores the accepted record behind an unapplied creation draft")
	_check(draft_restarted.curve_creator.active and draft_restarted.curve_creator.draft == studio.curve_creator.draft and draft_restarted.canvas.pick_for_new_curve and draft_restarted.canvas.curve_draft_cuts == studio.curve_creator.draft.cuts, "restart restores every literal new-curve field and resumes cut picking")
	_check(draft_restarted.curve_inspector.drafts == sibling_drafts and not draft_restarted.history.can_undo(), "new-curve recovery preserves sibling drafts and exact empty command history")
	draft_restarted.queue_free()
	await process_frame
	studio.curve_creator.id_edit.text = "outerArc"
	studio.curve_creator._id_changed("outerArc")
	studio.curve_creator.start_spin.value = 0
	studio.curve_creator.end_spin.value = 7
	studio.curve_creator._start_changed(0)
	studio.curve_creator._end_changed(7)
	studio.curve_creator.direction_option.select(1)
	studio.curve_creator._direction_changed(1)
	studio.curve_creator._create()
	var arc_created_source: String = studio.document.to_json()
	_check(not studio.curve_creator.active and studio.document.data.curves[-1].id == "outerArc", "validated live arc creation appends the exact stable record")
	_check(studio.document.data.curves[-1].direction == "up" and studio.document.data.curves[-1].color == "#ff00d4", "live arc keeps literal orientation and thesis magenta")
	_check(studio.history.undo_stack.size() == 1 and studio.curve_inspector.drafts == sibling_drafts and studio.canvas.selected_record.id == "outerArc", "arc creation is one selected-ID command and preserves every sibling draft")
	_check(studio.geometry_result.ok and studio.record_list.item_count == 11, "created arc receives exact geometry and a stable inspector row")
	studio.curve_creator.start("loop")
	studio.curve_creator.id_edit.text = "outerLoop"
	studio.curve_creator._id_changed("outerLoop")
	studio.curve_creator.append_cut(0)
	studio.curve_creator.append_cut(6)
	studio.curve_creator.start_up_check.button_pressed = false
	studio.curve_creator._start_up_changed(false)
	studio.curve_creator._create()
	var curves_created_source: String = studio.document.to_json()
	_check(studio.document.data.curves[-1].id == "outerLoop" and studio.document.data.curves[-1].cuts == [0, 6] and studio.document.data.curves[-1].start_up == false, "validated live loop preserves exact ordered visits and orientation")
	_check(studio.history.undo_stack.size() == 2 and studio.curve_inspector.drafts == sibling_drafts and studio.geometry_result.ok, "loop creation is a second command without consuming other drafts")
	var curves_created_svg: String = studio.geometry_result.svg
	var curves_created_tikz: String = studio.geometry_result.tikz
	var created_recovery := WorkspaceRecovery.load_file()
	_check(created_recovery.ok and DiagramDocument.parse(created_recovery.history_state.current).document.to_json() == curves_created_source, "recovery checkpoint contains both newly accepted curves")
	var creation_restarted = packed.instantiate()
	root.add_child(creation_restarted)
	await process_frame
	_check(creation_restarted._restore_startup_recovery() and creation_restarted.document.to_json() == curves_created_source, "restart recovery reproduces newly created curves exactly")
	_check(creation_restarted.geometry_result.svg == curves_created_svg and creation_restarted.geometry_result.tikz == curves_created_tikz, "recovered creation reproduces byte-identical publication exports")
	creation_restarted.queue_free()
	await process_frame
	studio._undo()
	_check(studio.document.to_json() == arc_created_source and studio.document.data.curves[-1].id == "outerArc", "one undo removes only the loop creation")
	studio._undo()
	_check(studio.document.to_json() == creation_before, "second undo removes only the arc creation")
	studio._redo()
	studio._redo()
	_check(studio.document.to_json() == curves_created_source and studio.geometry_result.svg == curves_created_svg and studio.geometry_result.tikz == curves_created_tikz, "redo restores both creations and exact exports deterministically")
	studio.curve_inspector.clear_drafts()
	studio._save_path("user://ui-created-curves.json")
	_check(DiagramDocument.load_path("user://ui-created-curves.json").document.to_json() == curves_created_source, "created arc and loop save as exact mathematical JSON")
	studio._open_path("user://ui-created-curves.json")
	_check(studio.document.to_json() == curves_created_source and studio.geometry_result.svg == curves_created_svg and studio.geometry_result.tikz == curves_created_tikz, "save and reopen reproduce both created curves and publication exports")
	DirAccess.remove_absolute(ProjectSettings.globalize_path("user://ui-created-curves.json"))
	studio._open_resource("res://fixtures/braid-v1.json")
	await process_frame
	_check(studio.document.data.kind == "braid", "braid fixture switches view")
	_check(studio.record_list.item_count == 6, "braid inspector shows summary and five crossings")
	studio.record_list.select(1)
	studio.record_list.item_selected.emit(1)
	_check(studio.canvas.selected_record.kind == "crossing" and studio.canvas.selected_record.index == 0, "braid inspector selects exact crossing index")
	var before: String = studio.document.to_json()
	_check(studio.braid_editor.visible and studio.braid_editor.step == 5 and studio.canvas.braid_step == 5, "braid workspace opens at final supplied configuration")
	_check("[2, 3, 4, 5, 6, 1]" in studio.braid_editor.detail.text and studio.braid_editor.index_spin.value == 0, "live inspector shows transported final identities and selected crossing")
	var braid_exact_svg: String = studio.geometry_result.svg
	studio.braid_editor.set_step(2)
	_check(studio.braid_editor.step == 2 and studio.canvas.braid_step == 2 and "[2, 3, 1, 4, 5, 6]" in studio.braid_editor.detail.text, "live timeline scrubs to independently known prefix")
	studio.braid_editor.set_direction("top-to-bottom")
	_check(studio.canvas.braid_presentation == "top-to-bottom" and studio.document.to_json() == before and studio.geometry_result.svg == braid_exact_svg, "presentation toggle changes schematic view without altering mathematical record or export")
	studio.braid_editor.generator_spin.value = 0
	studio._edit_braid_word("replace", 0, 0)
	_check(studio.document.to_json() == before and not studio.history.can_undo() and studio.braid_editor.step == 2, "rejected zero crossing leaves source, history, and timeline intact")
	studio._edit_braid_word("insert", 1, -1)
	var braid_inserted: String = studio.document.to_json()
	_check(studio.document.data.braid.word == [1, -1, -2, 3, -4, 5] and studio.history.undo_stack.size() == 1, "live braid insert is a literal one-command signed word edit")
	_check(studio.braid_editor.direction == "top-to-bottom" and studio.canvas.braid_step == 2 and studio.canvas.selected_record.index == 1 and studio.geometry_result.ok, "edit preserves presentation and selects new crossing with Python geometry")
	studio._edit_braid_word("replace", 1, 2)
	_check(studio.document.data.braid.word == [1, 2, -2, 3, -4, 5] and studio.history.undo_stack.size() == 2, "live replace changes only one signed generator without cancellation")
	studio._edit_braid_word("delete", 1, 0)
	var braid_deleted: String = studio.document.to_json()
	_check(studio.document.data.braid.word == [1, -2, 3, -4, 5] and studio.history.undo_stack.size() == 3, "live delete removes only one indexed crossing")
	studio.braid_editor.set_step(5)
	studio.braid_editor.toggle_play()
	studio.braid_editor.advance(1.8)
	_check(studio.braid_editor.step == 3 and studio.canvas.braid_step == 3 and studio.document.to_json() == braid_deleted, "playback from final step reaches exact third prefix without editing source")
	studio.braid_editor.set_step(1)
	_check(not studio.braid_editor.playing and studio.canvas.braid_step == 1, "manual scrub stops playback at exact requested prefix")
	studio._undo()
	_check(studio.document.data.braid.word == [1, 2, -2, 3, -4, 5] and not studio.braid_editor.playing and studio.braid_editor.direction == "top-to-bottom", "undo stops playback and restores literal previous word with view direction")
	studio._undo()
	studio._undo()
	_check(studio.document.to_json() == before and studio.geometry_result.svg == braid_exact_svg, "three undos recover byte-identical source and publication SVG")
	studio._redo()
	studio._redo()
	studio._redo()
	_check(studio.document.to_json() == braid_deleted and studio.braid_editor.direction == "top-to-bottom", "redos restore exact command sequence without changing presentation")
	studio._edit_braid_word("replace", 4, -5)
	var braid_final: String = studio.document.to_json()
	_check(studio.document.data.braid.word == [1, -2, 3, -4, -5] and braid_final != before, "later signed replacement remains a genuine unsaved edit")
	studio.braid_editor.set_direction("top-to-bottom")
	studio.braid_editor.set_playhead(2.25)
	studio._persist_recovery()
	var braid_recovery := WorkspaceRecovery.load_file()
	_check(braid_recovery.ok and braid_recovery.found and braid_recovery.history_state.undo.size() == 4, "braid word commands are stored in separate bounded desktop recovery")
	_check(braid_recovery.view_state.braid.playhead == 2.25 and braid_recovery.view_state.braid.presentation == "top-to-bottom", "braid recovery stores fractional playback and presentation outside the signed word")
	var braid_restarted = packed.instantiate()
	root.add_child(braid_restarted)
	await process_frame
	_check(braid_restarted._restore_startup_recovery() and braid_restarted.document.to_json() == braid_final, "restart restores edited braid and exact signed word")
	_check(braid_restarted.geometry_result.svg == studio.geometry_result.svg and braid_restarted.history.can_undo(), "recovered braid has matching Python geometry and working history")
	_check(braid_restarted.braid_editor.playhead == 2.25 and braid_restarted.braid_editor.direction == "top-to-bottom" and braid_restarted.canvas.braid_playhead == 2.25, "restart restores deterministic fractional braid view state without changing the word")
	braid_restarted.queue_free()
	await process_frame
	studio._save_path("user://ui-braid-edited.json")
	_check(DiagramDocument.load_path("user://ui-braid-edited.json").document.to_json() == braid_final, "signed word saves and reopens as exact version-1 recipe")
	studio._open_path("user://ui-braid-edited.json")
	_check(studio.document.to_json() == braid_final and studio.geometry_result.ok and studio.braid_editor.direction == "bottom-to-top", "reopened braid restores source direction and Python geometry")
	DirAccess.remove_absolute(ProjectSettings.globalize_path("user://ui-braid-edited.json"))
	before = studio.document.to_json()
	studio.canvas.zoom_at(Vector2(80, 60), 1.2)
	studio.canvas.pan = Vector2(12, -7)
	_check(studio.document.to_json() == before, "navigation keeps source record exact")
	studio._open_result({"ok": false, "error": "test rejection"}, "bad.json")
	_check(studio.document.to_json() == before, "rejected open retains current document")
	_check("Not opened" in studio.status_label.text, "rejected open is visible")
	studio.queue_free()
	await process_frame
	_finish()

func _check(condition: bool, label: String) -> void:
	assertions += 1
	if not condition:
		failures += 1
		printerr("FAIL: " + label)

func _finish() -> void:
	if failures:
		printerr("UI SMOKE FAILED: %d of %d assertions" % [failures, assertions])
		quit(1)
	else:
		print("UI SMOKE PASS: %d assertions" % assertions)
		quit(0)
