extends SceneTree

const DiagramDocumentClass = preload("res://scripts/diagram_document.gd")
const WorkspaceRecoveryClass = preload("res://scripts/workspace_recovery.gd")

var failures := 0
var assertions := 0

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	root.size = Vector2i(1280, 800)
	var studio = load("res://scenes/studio.tscn").instantiate()
	# Exercises browser-specific controller paths in the native headless runtime.
	# This does not claim to execute WebAssembly, DOM dialogs, or WebGL rendering.
	studio.browser_mode = true
	root.add_child(studio)
	await process_frame
	_check(studio.document != null, "web-mode fixture loads without Python")
	_check(not studio.geometry_result.ok, "web mode never claims certified geometry")
	_check(studio.svg_button.disabled and studio.tikz_button.disabled, "exact exports disabled")
	_check(not studio.browser_drafts.button_pressed, "unvalidated edits require opt in")
	_check(studio.browser_file_menu.get_popup().item_count == 4 and studio.browser_file_menu.custom_minimum_size.y >= 44, "browser file actions share one touch-sized compact menu")
	_check(not studio.browser_unsaved_state, "fresh browser fixture has no unload warning")
	var before: String = studio.document.to_json()
	var x: float = studio.document.data.surface.objects[1].x + 0.1
	studio._canvas_edit_commit("object", "p2", Vector2(x, 0))
	_check(studio.document.to_json() == before and not studio.history.can_undo(), "default rejects unvalidated edit without history")
	studio.browser_drafts.button_pressed = true
	studio._canvas_edit_commit("object", "p2", Vector2(x, 0))
	var after: String = studio.document.to_json()
	_check(after != before and "UNVALIDATED" in studio.status_label.text, "opted-in draft is visibly unvalidated")
	_check(studio.browser_unsaved_state, "accepted browser edit activates unload warning")
	_check(not studio.geometry_result.ok and studio.svg_button.disabled, "edit does not fabricate geometry")
	_check(studio.document.data.curves[0].start == 1 and studio.document.data.curves[0].cuts == [], "draft preserves itinerary and endpoints")
	studio._undo()
	_check(studio.document.to_json() == before, "browser-mode undo restores exact source")
	_check(not studio.browser_unsaved_state, "undo to downloaded baseline clears unload warning")
	studio._redo()
	_check(studio.document.to_json() == after, "browser-mode redo restores draft")
	_check(studio.browser_unsaved_state, "redo away from baseline restores unload warning")
	var workspace_backup: Dictionary = studio._encode_browser_workspace()
	var parsed_backup: Dictionary = WorkspaceRecoveryClass.parse(workspace_backup.get("text", ""))
	_check(workspace_backup.ok and parsed_backup.ok and parsed_backup.history_state.undo.size() == 1, "browser workspace backup is the strict bounded recovery format with exact history")
	_check(DiagramDocumentClass.parse(parsed_backup.history_state.current).document.to_json() == after and parsed_backup.baseline_source == before, "browser workspace backup preserves exact accepted current and baseline records")
	studio._undo()
	studio._browser_local_workspace_received([workspace_backup.text, ""])
	_check(studio.startup_recovery_browser and not studio.startup_recovery.is_empty() and "browser-local" in studio.recovery_dialog.dialog_text, "valid origin-local recovery is offered explicitly rather than silently replacing the initial record")
	_check(studio.document.to_json() == before, "offered origin-local recovery leaves the visible accepted record unchanged")
	_check(studio._restore_startup_recovery() and studio.document.to_json() == after and not studio.startup_recovery_browser, "explicit origin-local restore recovers exact accepted state and clears its pending origin marker")
	studio._undo()
	studio._browser_workspace_received([workspace_backup.text, ""])
	_check(studio.document.to_json() == after and studio.history.can_undo() and "Restored complete browser workspace" in studio.status_label.text, "explicit browser workspace restore recovers exact accepted state and history")
	var before_invalid_workspace: String = studio.document.to_json()
	studio._browser_workspace_received(["{\"format\":\"not-a-workspace\"}", ""])
	_check(studio.document.to_json() == before_invalid_workspace and "current workspace is unchanged" in studio.status_label.text, "invalid browser workspace fails closed without mutation")
	studio._browser_local_workspace_received(["{\"format\":\"not-a-workspace\"}", ""])
	_check(studio.document.to_json() == before_invalid_workspace and "invalid local browser recovery" in studio.status_label.text, "invalid origin-local recovery fails closed without mutating the open record")
	studio._browser_local_workspace_written(["Persistent browser storage is unavailable."])
	_check(studio.browser_unsaved_state and "download a complete workspace backup" in studio.status_label.text, "local storage failure keeps the unload warning and provides a portable-backup fallback")
	studio.browser_unsaved_state = false
	studio._browser_local_workspace_written(["Local recovery changed in another Studio tab."])
	_check("existing local recovery was preserved" in studio.status_label.text, "a clean stale tab reports that it preserved a newer local recovery instead of claiming unsaved in-memory work")
	studio._sync_browser_unload_guard()
	studio._canvas_edit_commit("object", "p2", Vector2(99999, 0))
	_check(studio.document.to_json() == after, "draft mode still rejects order/ellipse violation")
	studio._browser_file_received(["{\"version\":999}", ""])
	_check(studio.document.to_json() == after, "invalid upload retains current draft")
	studio._browser_file_received(["", "file read failed"])
	_check(studio.document.to_json() == after and "file read failed" in studio.status_label.text, "read failure preserves data and reports error")
	studio._browser_file_received(["", ""])
	_check(studio.document.to_json() == after, "cancel preserves data")
	studio._browser_file_received([before, ""])
	_check(studio.document.to_json() == before and not studio.history.can_undo(), "bounded upload opens exact recipe with fresh history")
	_check(not studio.browser_unsaved_state, "successful browser open establishes a clean baseline")
	_check(not studio.browser_drafts.button_pressed, "opening a file resets experimental consent")
	studio._show_open()
	_check("unavailable" in studio.status_label.text, "missing DOM adapter is explicit")
	studio._show_save()
	_check("unavailable" in studio.status_label.text, "missing download adapter is explicit")
	studio._open_resource("res://fixtures/multi-curve-v1.json")
	var multi_initial: String = studio.document.to_json()
	studio.curve_creator.start("arc")
	_check(studio.browser_unsaved_state, "unapplied new-curve draft activates unload warning")
	workspace_backup = studio._encode_browser_workspace()
	parsed_backup = WorkspaceRecoveryClass.parse(workspace_backup.get("text", ""))
	_check(parsed_backup.ok and parsed_backup.creation_state.active and parsed_backup.creation_state.draft == studio.curve_creator.draft, "browser workspace backup retains the complete literal unapplied new-curve draft")
	studio.curve_creator._create()
	_check(studio.document.to_json() == multi_initial and studio.curve_creator.active and not studio.history.can_undo(), "browser curve creation requires explicit unvalidated-edit opt in")
	studio.browser_drafts.button_pressed = true
	studio.curve_creator._create()
	_check(studio.document.data.curves[-1].id == "arc1" and "UNVALIDATED" in studio.status_label.text and not studio.geometry_result.ok, "browser arc creation is explicitly unvalidated and never fabricates geometry")
	_check(studio.history.undo_stack.size() == 1 and studio.document.data.curves[-1].start == 0 and studio.document.data.curves[-1].end == 7, "browser arc creation remains one exact command")
	studio._undo()
	_check(studio.document.to_json() == multi_initial, "browser curve creation undo restores exact original record")
	studio.browser_drafts.button_pressed = false
	studio.record_list.item_selected.emit(0)
	studio._request_reindex(1)
	_check(studio.pending_reindex.is_empty() and studio.document.to_json() == multi_initial, "browser reindex requires explicit unvalidated-edit opt in")
	studio.browser_drafts.button_pressed = true
	studio._request_reindex(1)
	_check(not studio.pending_reindex.is_empty() and studio.document.to_json() == multi_initial, "browser reindex is still a non-mutating confirmation proposal")
	studio._confirm_reindex()
	_check(studio.document.data.surface.objects[0].id == "p2" and "UNVALIDATED" in studio.status_label.text and not studio.geometry_result.ok, "browser reindex remains explicitly unvalidated")
	studio._undo()
	_check(studio.document.to_json() == multi_initial, "browser reindex undo restores exact original order")
	studio.browser_drafts.button_pressed = false
	studio.record_list.item_selected.emit(7)
	var multi_source: String = studio.document.to_json()
	studio.curve_inspector.append_cut(5)
	studio.curve_inspector._apply()
	_check(studio.document.to_json() == multi_source and not studio.history.can_undo(), "browser itinerary edit requires opt in")
	_check(studio.curve_inspector.draft_cuts == [0, 5], "browser rejection retains draft")
	studio.browser_drafts.button_pressed = true
	studio.curve_inspector._apply()
	_check(studio.document.data.curves[1].cuts == [0, 5] and "UNVALIDATED" in studio.status_label.text, "browser record acceptance never claims routing success")
	_check(not studio.geometry_result.ok and studio.svg_button.disabled and studio.tikz_button.disabled, "browser itinerary edit leaves exact exports disabled")
	studio._undo()
	_check(studio.document.to_json() == multi_source, "browser itinerary undo restores exact record")
	studio.curve_inspector.append_cut(0)
	studio.curve_inspector._apply()
	_check(studio.document.to_json() == multi_source and studio.curve_inspector.draft_cuts == [0, 0], "browser opt in does not permit nonminimal record")
	studio._open_resource("res://fixtures/braid-v1.json")
	_check(studio.document.to_json() == multi_source and studio.pending_action.is_valid(), "web mode also guards unapplied drafts before fixture replacement")
	studio._discard_and_continue()
	_check(studio.document.data.kind == "braid" and studio.record_list.item_count == 6, "braid view remains available without Python")
	var braid_source: String = studio.document.to_json()
	studio.braid_editor.set_playhead(1.75)
	studio.braid_editor.set_direction("top-to-bottom")
	_check(studio.canvas.braid_playhead == 1.75 and studio.document.to_json() == braid_source, "browser fractional playback keeps exact source outside view state")
	_check(studio.canvas.select_braid_crossing(studio.canvas.screen_position_for_crossing(1)) and studio.braid_editor.index_spin.value == 1, "browser canvas picks visible partial crossing without Python")
	_check(not studio.geometry_result.ok and studio.svg_button.disabled and studio.tikz_button.disabled, "fractional browser preview never enables publication geometry")
	studio._edit_braid_word("insert", 1, -1)
	_check(studio.document.to_json() == braid_source and not studio.history.can_undo(), "browser braid word edit requires explicit opt in")
	studio.browser_drafts.button_pressed = true
	studio._edit_braid_word("insert", 1, -1)
	_check(studio.document.data.braid.word == [1, -1, -2, 3, -4, 5] and "UNVALIDATED" in studio.status_label.text, "browser signed braid edit is visibly unvalidated")
	_check(not studio.geometry_result.ok and studio.svg_button.disabled and studio.tikz_button.disabled, "browser braid editor cannot enable publication geometry")
	studio._undo()
	_check(studio.document.to_json() == braid_source, "browser signed braid undo restores exact source")
	studio.queue_free()
	await process_frame
	print("WEB MODE CONTROLLER: %d assertions, %d failures" % [assertions, failures])
	quit(1 if failures else 0)

func _check(condition: bool, label: String) -> void:
	assertions += 1
	if not condition:
		failures += 1
		printerr("FAIL: " + label)
